export const mockUser = {
  id: "user_1",
  name: "John Doe",
  email: "john@example.com",
  image: null,
  isPro: false,
};

export const mockItemTypes = [
  { id: "type_snippet", name: "snippet", icon: "Code", color: "#3b82f6", isSystem: true },
  { id: "type_prompt", name: "prompt", icon: "Sparkles", color: "#8b5cf6", isSystem: true },
  { id: "type_command", name: "command", icon: "Terminal", color: "#f97316", isSystem: true },
  { id: "type_note", name: "note", icon: "StickyNote", color: "#fde047", isSystem: true },
  { id: "type_file", name: "file", icon: "File", color: "#6b7280", isSystem: true },
  { id: "type_image", name: "image", icon: "Image", color: "#ec4899", isSystem: true },
  { id: "type_link", name: "link", icon: "Link", color: "#10b981", isSystem: true },
];

export const mockItems = [
  {
    id: "item_1",
    title: "useAuth Hook",
    description: "Custom authentication hook for React applications",
    contentType: "TEXT" as const,
    content: `import { useState, useEffect } from 'react';\n\nexport function useAuth() {\n  const [user, setUser] = useState(null);\n  const [loading, setLoading] = useState(true);\n\n  useEffect(() => {\n    // fetch session\n  }, []);\n\n  return { user, loading };\n}`,
    language: "typescript",
    url: null,
    isFavorite: false,
    isPinned: true,
    userId: "user_1",
    itemTypeId: "type_snippet",
    tags: ["react", "auth", "hooks"],
    createdAt: new Date("2025-01-15"),
    updatedAt: new Date("2025-01-15"),
  },
  {
    id: "item_2",
    title: "API Error Handling Pattern",
    description: "Fetch wrapper with exponential backoff retry logic",
    contentType: "TEXT" as const,
    content: `async function fetchWithRetry(url, retries = 3) {\n  for (let i = 0; i < retries; i++) {\n    try {\n      const res = await fetch(url);\n      if (!res.ok) throw new Error(res.statusText);\n      return await res.json();\n    } catch (e) {\n      if (i === retries - 1) throw e;\n      await new Promise(r => setTimeout(r, 2 ** i * 1000));\n    }\n  }\n}`,
    language: "javascript",
    url: null,
    isFavorite: false,
    isPinned: true,
    userId: "user_1",
    itemTypeId: "type_snippet",
    tags: ["api", "error-handling"],
    createdAt: new Date("2025-01-12"),
    updatedAt: new Date("2025-01-12"),
  },
  {
    id: "item_3",
    title: "Git Reset Hard",
    description: "Discard all local changes and reset to origin",
    contentType: "TEXT" as const,
    content: "git reset --hard origin/main",
    language: null,
    url: null,
    isFavorite: true,
    isPinned: false,
    userId: "user_1",
    itemTypeId: "type_command",
    tags: ["git"],
    createdAt: new Date("2025-01-10"),
    updatedAt: new Date("2025-01-10"),
  },
  {
    id: "item_4",
    title: "Docker Compose Up",
    description: "Start all services defined in docker-compose.yml",
    contentType: "TEXT" as const,
    content: "docker compose up -d --build",
    language: null,
    url: null,
    isFavorite: false,
    isPinned: false,
    userId: "user_1",
    itemTypeId: "type_command",
    tags: ["docker", "devops"],
    createdAt: new Date("2025-01-08"),
    updatedAt: new Date("2025-01-08"),
  },
  {
    id: "item_5",
    title: "Code Review Prompt",
    description: "Curated AI prompt for thorough code review",
    contentType: "TEXT" as const,
    content: "Review the following code for: security vulnerabilities, performance issues, code clarity, and adherence to best practices. Provide specific, actionable feedback for each issue found.",
    language: null,
    url: null,
    isFavorite: true,
    isPinned: false,
    userId: "user_1",
    itemTypeId: "type_prompt",
    tags: ["code-review", "ai"],
    createdAt: new Date("2025-01-05"),
    updatedAt: new Date("2025-01-05"),
  },
  {
    id: "item_6",
    title: "Explain Like I'm Five",
    description: "Simplify complex concepts for non-technical stakeholders",
    contentType: "TEXT" as const,
    content: "Explain the following concept as if you're talking to a 5-year-old with no technical background. Use simple analogies and avoid jargon.",
    language: null,
    url: null,
    isFavorite: false,
    isPinned: false,
    userId: "user_1",
    itemTypeId: "type_prompt",
    tags: ["ai", "communication"],
    createdAt: new Date("2025-01-03"),
    updatedAt: new Date("2025-01-03"),
  },
  {
    id: "item_7",
    title: "Python List Comprehension",
    description: "Common Python list comprehension patterns",
    contentType: "TEXT" as const,
    content: "squares = [x**2 for x in range(10)]\neven_squares = [x**2 for x in range(10) if x % 2 == 0]\nflat = [x for row in matrix for x in row]",
    language: "python",
    url: null,
    isFavorite: false,
    isPinned: false,
    userId: "user_1",
    itemTypeId: "type_snippet",
    tags: ["python", "patterns"],
    createdAt: new Date("2024-12-28"),
    updatedAt: new Date("2024-12-28"),
  },
  {
    id: "item_8",
    title: "Tailwind Dark Mode Config",
    description: "Setup Tailwind CSS dark mode with class strategy",
    contentType: "TEXT" as const,
    content: "module.exports = {\n  darkMode: 'class',\n  // ...\n}",
    language: "javascript",
    url: null,
    isFavorite: false,
    isPinned: false,
    userId: "user_1",
    itemTypeId: "type_snippet",
    tags: ["tailwind", "css"],
    createdAt: new Date("2024-12-20"),
    updatedAt: new Date("2024-12-20"),
  },
  {
    id: "item_9",
    title: "Next.js Docs",
    description: "Official Next.js documentation",
    contentType: "LINK" as const,
    content: null,
    language: null,
    url: "https://nextjs.org/docs",
    isFavorite: true,
    isPinned: false,
    userId: "user_1",
    itemTypeId: "type_link",
    tags: ["nextjs", "docs"],
    createdAt: new Date("2024-12-15"),
    updatedAt: new Date("2024-12-15"),
  },
  {
    id: "item_10",
    title: "Git Interactive Rebase",
    description: "Squash and reorder commits before pushing",
    contentType: "TEXT" as const,
    content: "git rebase -i HEAD~3",
    language: null,
    url: null,
    isFavorite: false,
    isPinned: false,
    userId: "user_1",
    itemTypeId: "type_command",
    tags: ["git"],
    createdAt: new Date("2024-12-10"),
    updatedAt: new Date("2024-12-10"),
  },
];

export const mockCollections = [
  {
    id: "col_1",
    name: "React Patterns",
    description: "Common React patterns and hooks",
    isFavorite: true,
    userId: "user_1",
    itemIds: ["item_1", "item_2", "item_8"],
    createdAt: new Date("2025-01-01"),
    updatedAt: new Date("2025-01-15"),
  },
  {
    id: "col_2",
    name: "Python Snippets",
    description: "Useful Python code snippets",
    isFavorite: false,
    userId: "user_1",
    itemIds: ["item_7"],
    createdAt: new Date("2025-01-01"),
    updatedAt: new Date("2024-12-28"),
  },
  {
    id: "col_3",
    name: "Context Files",
    description: "AI context files for projects",
    isFavorite: false,
    userId: "user_1",
    itemIds: ["item_5", "item_6", "item_9"],
    createdAt: new Date("2025-01-01"),
    updatedAt: new Date("2025-01-05"),
  },
  {
    id: "col_4",
    name: "Interview Prep",
    description: "Technical interview preparation",
    isFavorite: true,
    userId: "user_1",
    itemIds: ["item_1", "item_7", "item_5", "item_6"],
    createdAt: new Date("2024-12-01"),
    updatedAt: new Date("2025-01-03"),
  },
  {
    id: "col_5",
    name: "Git Commands",
    description: "Frequently used git commands",
    isFavorite: true,
    userId: "user_1",
    itemIds: ["item_3", "item_4", "item_10"],
    createdAt: new Date("2024-12-01"),
    updatedAt: new Date("2025-01-10"),
  },
  {
    id: "col_6",
    name: "AI Prompts",
    description: "Curated AI prompts for coding",
    isFavorite: false,
    userId: "user_1",
    itemIds: ["item_5", "item_6"],
    createdAt: new Date("2024-12-01"),
    updatedAt: new Date("2025-01-05"),
  },
];
